### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by KonajuGames** [Redth/Resizetizer#1]
I thought I'd give this a try, but all can get is "Index was outside the bounds of the array".  The full error output in the build log is.

    1>C:\Projects\MyApp\Src\packages\Resizetizer.0.1.2\build\Resizetizer.targets(34,3): error : Index was outside the bounds of the array.

I tried it with Resizetizer in the UI portable project building both Android and iOS files, and also with Resizetizer separately in both the UI.Droid and UI.iOS projects.  The resizetizer.yaml file for the UI.Droid project is just a simple config.

````
- platform: Android
  outputBasePath: "./Resources/"
  assets:
   - file: "./Back.svg"
     size: 24x24
  outputs:
   - path: "./drawable-mdpi"
     ratio: 1.0
   - path: "./drawable-hdpi"
     ratio: 1.5
   - path: "./drawable-xhdpi"
     ratio: 2.0
   - path: "./drawable-xxhdpi"
     ratio: 3.0
   - path: "./drawable-xxxhdpi"
     ratio: 4.0
````

Also, you should another step to installation.

  3. Restart Visual Studio to get the ResizetizerConfig build action to show up in the properties list.

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
