### ISSUE TITLE
Super sampling does not work

### ISSUE THREAD

**Issue by Cheesebaron** [Redth/Resizetizer#3]
Since we cannot do Anti Aliasing (#2) I was trying to do some super sampling with a config looking like this:

```
- platform: iOS
  outputBasePath: "./"
  assets:
   - file: "./ToResize/image.svg"
     size: 400x400
  outputs:
   - ratio: 0.1
   - fileSuffix: "@2x"
     ratio: 0.2
   - fileSuffix: "@3x"
     ratio: 0.3
```

I would in this case expect the @1x resource to be 40x40, @2x to be 80x80 and @3x to be 120x120. However, it seems to ignore this and give me 400x400, 800x800 and 1200x1200 as output instead.
